### ISSUE TITLE
register

### ISSUE THREAD

**Issue by Roger-luo** [MasonProtter/LegibleLambdas.jl#11]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@MasonProtter is the registrator installed?

**Comment by MasonProtter** [comment]
It is now!

@JuliaRegistrator register

**Comment by Roger-luo** [comment]
oh it seems we had julia=1.0.0 in previous versions? I guess we should tag a new major version with julia = "1" instead then?
